### ISSUE TITLE
Determine the initial set of Satellites for production

### ISSUE THREAD

**Issue by comzeradd** [satnogs/satnogs-network#103]
[Hint](https://github.com/satnogs/satnogs-network/blob/master/network/base/tests/__init__.py#L49)

@ppapadeas i'll need some help with that

**Comment by ppapadeas** [comment]
https://gist.github.com/ppapadeas/694d15feeeffd50b0a30

Cheers.

**Comment by comzeradd** [comment]
Cool. We'll use fetch_tle command to initialize them. I'm keeping this open till we deploy on production.

**Comment by comzeradd** [comment]
Closing this in favor of #120. The fixtures for initial Satellite data is tracked on the [DB side](https://github.com/satnogs/satnogs-db/issues/7).
