### ISSUE TITLE
Parse gpredict transpoder data

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-network#11]
To inform our model, we need to extract the schema and unique values of transponder files (serialized) here:
http://sourceforge.net/p/gpredict/code/ci/master/tree/data/trsp/

**Comment by comzeradd** [comment]
Do we have any code on that on [satnogs-software repo](https://github.com/satnogs/satnogs-software/)? @jinxcat @ppapadeas

**Comment by comzeradd** [comment]
Network should fetch these from DB. So, closing this in favor of #110 and relevant [db issue](https://github.com/satnogs/satnogs-db/issues/7).
