### ISSUE TITLE
Support for fixed stations

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-network#128]
Some people may want to participate in SatNOGS but only have means for a fixed station.  Such a fixed station would be very limited in comparison to a full AZ/EL rotor station, but is better than no station at all.

This was the idea behind entry into carpcomm, a simple yagi pointed 30 degrees up and +/- 30 degrees AZ to catch passes as they ascend/descend:

![carpcomm antenna](https://1.bp.blogspot.com/-P-E4JLlVcSo/USI9461gPiI/AAAAAAAAAF4/CC5TUDI7DTE/s1600/IMG_20130128_123239.jpg)
(carpcomm antenna from http://blog.carpcomm.com/)

To support this in the network would just be some configuration that notes it is a fixed station, and what direction it is facing for observation calculations   (this could also tie in with the last 2 issues I just filed, #126 #127 ).  Those calculations would just have to account for a much smaller, directional window which may or may not be easy to do.

If we decide to go with this, satnogs-client would need a configuration to skip all rotor control as well, otherwise everything else would be the same.

**Comment by cshields** [comment]
I should also add that this does not have to be a fixed-yagi either..  Some people have eggbeater antennas and others that are omnidirectional and could serve SatNOGS with data, without needing a rotor.  In this case, there would be no need for a change in satnogs-network, just a need to ignore rotor controls in satnogs-client.

**Comment by papamat** [comment]
Is good to consider azimuth only rotators too.

**Comment by cshields** [comment]
fixed in v0.2.5
