### ISSUE TITLE
Replace fig with docker-compose

### ISSUE THREAD

**Issue by comzeradd** [satnogs/satnogs-network#151]

**Comment by cshields** [comment]
@comzeradd I don't know how attached you are to centos7 for docker, but the above commit fixes the issues in moving to docker-compose and speeds the build up by switching to debian (the python2.7 hub image).  Feel free to kick it out if you want to fix this by sticking with centos7.

**Comment by comzeradd** [comment]
I run this branch and the web container image is only 60MB smaller than the centos one. In any case I prefer the docker setup to be as close to production as possible and at the moment we run centos at production.
