### ISSUE TITLE
Add UTC info to list "Latest Observations" and "Scheduled Observations"

### ISSUE THREAD

**Issue by rkiendl** [satnogs/satnogs-network#157]
to enhance reading of the Latest or Scheduled Observations list the info [UTC] in field Timeframe would be usefull.
this would take the Chance of Interpretation which time is mentioned. This because the hint UTC  is only given during add new Observation  for logged on users.

**Comment by cshields** [comment]
We can add the tag for clarification quickly and easily.

Instead, should we add a timezone option to each user's settings in the network - allowing them to change all views to their local (or any other) time zone?

The only down side to this would be in sharing information during collaborations - "I have a pass coming at 2103" could be misunderstood unless the timezone is standardized.

@comzeradd ?
