### ISSUE TITLE
Fix user link on front page

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-network#168]
Front page, scheduled operations tab, should have users linked.

![screenshot from 2015-09-26 14-38-10](https://cloud.githubusercontent.com/assets/498592/10119160/5fb87c82-645c-11e5-871c-3afe171a8c3f.png)

**Comment by mccolgst** [comment]
Hi folks, not sure if you saw this one yet but I added a PR here for this: 
https://github.com/satnogs/satnogs-network/pull/172
Let me know what you think :)

**Comment by comzeradd** [comment]
Fixed at 25b78cf30519333ee28d7f2ad2602c7868780f54
