### ISSUE TITLE
Store historical TLEs

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-network#173]
Every time we fetch TLEs we should be storing the old ones with timestamp.
Probably amending the current model or creating a new one?

**Comment by comzeradd** [comment]
You mean keep a full history of TLEs? That would significantly increase database size and performance. Why do we need this?

**Comment by ppapadeas** [comment]
because of this #174 :)

**Comment by comzeradd** [comment]
Ok, that makes sense. So we need to store TLEs as part of an observation, not all TLEs.

**Comment by comzeradd** [comment]
Let's consolidate all TLE/observation enhancements under #174.
