### ISSUE TITLE
Keep epoch time of TLE involved in an observation

### ISSUE THREAD

**Issue by comzeradd** [satnogs/satnogs-network#177]
@ppapadeas I'll need your input here

**Comment by ppapadeas** [comment]
Columns 19-32 on Line 1
19–20 	Epoch Year (last two digits of year) 	e.g. 08
21–32 	Epoch (day of the year and fractional portion of the day) 	e.g. 264.51782528

**Comment by comzeradd** [comment]
Closing this in favor of #174. If we keep and display TLE used for a specific observation we can display epoch time too.
