### ISSUE TITLE
Ground Station Edit/Add Field Validation

### ISSUE THREAD

**Issue by angrymeerkat** [satnogs/satnogs-network#186]
https://community.satnogs.org/t/problem-adding-ground-station/521

Field validation should be displayed or shown before allowing a ground station to be added. This stems from the altitude field accepting decimal input and causes an add/edit failure due to the data type being an integer.

**Comment by angrymeerkat** [comment]
![validation_error](https://cloud.githubusercontent.com/assets/5695372/12077018/80336990-b17d-11e5-9fea-df881cc1afb4.png)

Potential stopgap measure. I'm not sure how to add input validation during data entry, but this seem to be more descriptive than the "Some fields .." error message.

**Comment by cshields** [comment]
In addition, if someone enters anything in addition to the integer for altitude (ie: "100m"), the error returned is that some fields are missing.  Should catch that this is something other than the integer and call it out.  See also https://community.satnogs.org/t/add-station-problem/562

![unnamed](https://cloud.githubusercontent.com/assets/225283/12867087/034ef7c8-ccb2-11e5-8274-ef5ca1422b3f.jpg)

**Comment by ppapadeas** [comment]
@comzeradd can you have a look at this?

**Comment by ryanturner** [comment]
This impacted me as well and resulted in a significant delay when trying to create my station.

**Comment by comzeradd** [comment]
I opened a PR for this. I added relevant attributes on the form (required and type) where applicable. So any modern browser (any but Safari) won't let you submit the form with errors. Additionally form errors are displayed on the alert message to help you correct them.
