### ISSUE TITLE
Expose the station to the API

### ISSUE THREAD

**Issue by ryanturner** [satnogs/satnogs-network#215]
Hi,

I'm working on scripting for station setup. In the Ansible role we have today, there are host vars for latitude, longitude, elevation, and station id. Since we already assume that the client is on the internet at setup time, and we're already asking for station ID (meaning they've already created a station), we should make a service call for the lat/lon/altitude rather than prompt the user. This means that the API needs to expose the station information.

**Comment by comzeradd** [comment]
Yes, that has already been considered and implemented through a Settings API endpoint. See [this commit](https://github.com/satnogs/satnogs-network/pull/164/commits/56df2e1f23c2467e965e8c5e7358f0b5e42af3d2). So the idea is that each station has a unique identifier (UIID). Filling this identifier to the Station form on network you can fetch all settings to client's configuration.

But in order for this to work we need to do the relevant work on the client side. So I'm closing this one and we monitor this through the relevant issue: satnogs/satnogs-client#67
