### ISSUE TITLE
Locator calculated wrong

### ISSUE THREAD

**Issue by dl1mx** [satnogs/satnogs-network#227]
While entering my groundstation details I found out that the calculation of the locator field is wrong. Instead of JO51DS it calculates HO51DS. Coordinates are N51.77733 E10.33085
73 de DL1MX
Marco

**Comment by cshields** [comment]
hmm. can reproduce. Will look into this.

**Comment by ppapadeas** [comment]
@cshields any updates on this?

**Comment by cshields** [comment]
Thanks Marco, sorry this has taken so long to fix it was really rather simple - there is a lookup table used in calculating the grid square and the entries were G H I H K L.... instead of G H I J K L....

:|

(thankfully the calculations are all correct)
