### ISSUE TITLE
Duplicate predictions on upcoming satellite passes

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-network#280]
On ground station pages, in the upcoming satellite passes section, sometimes duplicate predictions with slightly different details appear.

![duplicates](https://cloud.githubusercontent.com/assets/498592/22176314/fb984e40-e00f-11e6-9ba8-b502b6a01828.png)

Any ideas what might be causing this?

cc @boctok01 @cshields @comzeradd

**Comment by cshields** [comment]
(likely related to https://github.com/satnogs/satnogs-network/issues/199 )
