### ISSUE TITLE
Show recent/upcoming observations in station view

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-network#312]
We should make recent and upcoming observations assigned to a station easy to see from the station view.

Between myself and the SV1QVE station in prod I'm having to open each observation to see which are going to hit my station and which are assigned to SV1QVE.  Having a station-specific list in the station view would be very handy.

**Comment by comzeradd** [comment]
Fixed at d6e5bca502f6cbc0b145c12866044eca6336cc9b
