### ISSUE TITLE
Empty waveform and spectrogram when they are initialized before user visits audio tab

### ISSUE THREAD

**Issue by adamkalis** [satnogs/satnogs-network#314]
STR:

1. Open an observation
2. Wait until ogg file is loaded
3. Wait some more seconds for browser to analyzing the data and try to create waveform and spectrogram
4. Visit audio tab

Expected:
User should see waveform and spectrogram

Actual result:
User sees empty waveform and spectrogram

---------------------------------------

I have noticed that in case that waveform and spectrogram containers are not displayed (display: none on them or their parent), they can not (not sure why) load data into their canvas.

A quick hack could be to use "opacity: 0" instead "display: none".

**Comment by cshields** [comment]
we should prioritize this, new users have run into this bug this weekend..

**Comment by comzeradd** [comment]
It seems to be fixed on dev after 3b184701252fdacc4a3258cfe396edaf664e5ac9

@adamkalis can you confirm?

**Comment by adamkalis** [comment]
@comzeradd Yes I confirm that this is fixed in dev.
